export default {
  SET_USER_ID: 'SET_USER_ID',
  SET_USER_NAME: 'SET_USER_NAME',
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_USER_SN: 'SET_USER_SN',
  SET_ROLE_LIST: 'SET_ROLE_LIST',
  SET_ROLE_NAME: 'SET_ROLE_NAME',
  SET_ROLE_CODE: 'SET_ROLE_CODE'
}
